import type { Metadata } from "next";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api'
import "primereact/resources/themes/saga-green/theme.css";
import "primeflex/primeflex.css"
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <PrimeReactProvider>
          <div className="full-screen">
            <Navbar />
            {children}
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
